### ISSUE TITLE
zippyShare problem

### ISSUE THREAD

**Issue by ronitMaitra** [archertanu/mirror_gdrive_bot#3]
according to the log file the url is being generated as NULL so it won't work , please see to it
[log (1).txt](https://github.com/archertanu/mirror_gdrive_bot/files/5100758/log.1.txt)

**Comment by archertanu** [comment]
U cant just download from zippyshare.com u need to press that download button.so u hv 2 pass "Download Buttons" Copy link location...This is not even a issue..!!

**Comment by archertanu** [comment]
Issue Closed..!!
